export const threatTickerData = [
  { id: 1, contract: "0x7a250d...B4e33", protocol: "UniSwap V3 Fork", threat: "Reentrancy in withdraw()", risk: "CRITICAL", miner: "Miner-0xA3f", status: "CONFIRMED" },
  { id: 2, contract: "0x1f984...D2c91", protocol: "LendFi Protocol", threat: "Oracle Manipulation via flash loan", risk: "CRITICAL", miner: "Miner-0x8B2", status: "SIMULATING" },
  { id: 3, contract: "0xdead0...F1a23", protocol: "YieldVault DAO", threat: "Unchecked external call in stake()", risk: "MEDIUM", miner: "Miner-0xC7d", status: "CONFIRMED" },
  { id: 4, contract: "0x5c69b...3C2aB", protocol: "SwapX DEX", threat: "Integer overflow in calculateReward()", risk: "MEDIUM", miner: "Miner-0xE1f", status: "PENDING" },
  { id: 5, contract: "0x8888...4a2eF", protocol: "StablePool Finance", threat: "Privilege escalation in admin()", risk: "CRITICAL", miner: "Miner-0x2Aa", status: "CONFIRMED" },
  { id: 6, contract: "0xabcd...9f3B1", protocol: "BridgeLink Cross-chain", threat: "Cross-chain replay attack vector", risk: "CRITICAL", miner: "Miner-0xD4c", status: "SIMULATING" },
  { id: 7, contract: "0x3333...7e1C4", protocol: "NFT Marketplace Pro", threat: "Front-running vulnerability in bid()", risk: "LOW", miner: "Miner-0xF9a", status: "CONFIRMED" },
  { id: 8, contract: "0x9876...2d5A8", protocol: "Aave V4 Fork", threat: "Flash loan attack on liquidation()", risk: "CRITICAL", miner: "Miner-0xB5e", status: "CONFIRMED" },
];

export const minerLeaderboard = [
  { rank: 1, id: "Miner-0xA3f9", model: "DeepSeek-Audit-7B", exploits: 847, falsePositives: 12, responseTime: "1.2s", score: 98.6, reward: "2,450 TAO", trend: "up", status: "active" },
  { rank: 2, id: "Miner-0x8B2c", model: "Llama-Solidity-13B", exploits: 723, falsePositives: 18, responseTime: "1.8s", score: 97.5, reward: "2,180 TAO", trend: "up", status: "active" },
  { rank: 3, id: "Miner-0xC7d1", model: "GPT-Audit-Fine-v3", exploits: 691, falsePositives: 8, responseTime: "0.9s", score: 96.8, reward: "1,920 TAO", trend: "stable", status: "active" },
  { rank: 4, id: "Miner-0xE1f5", model: "CodeLlama-Security-34B", exploits: 654, falsePositives: 25, responseTime: "2.1s", score: 95.2, reward: "1,750 TAO", trend: "down", status: "active" },
  { rank: 5, id: "Miner-0x2Aa8", model: "Mixtral-Audit-8x7B", exploits: 612, falsePositives: 15, responseTime: "1.5s", score: 94.7, reward: "1,680 TAO", trend: "up", status: "active" },
  { rank: 6, id: "Miner-0xD4c3", model: "DeepSeek-Exploit-14B", exploits: 589, falsePositives: 30, responseTime: "2.4s", score: 93.1, reward: "1,520 TAO", trend: "down", status: "active" },
  { rank: 7, id: "Miner-0xF9a2", model: "Phi-Security-3B", exploits: 534, falsePositives: 9, responseTime: "0.7s", score: 92.8, reward: "1,380 TAO", trend: "up", status: "active" },
  { rank: 8, id: "Miner-0xB5e7", model: "Qwen-Audit-72B", exploits: 498, falsePositives: 22, responseTime: "3.1s", score: 91.3, reward: "1,240 TAO", trend: "stable", status: "idle" },
];

export const validatorData = [
  { id: "Val-0x1A", weight: 0.18, simulations: 12450, consensusRate: 99.2, stake: "15,000 TAO", status: "active" },
  { id: "Val-0x2B", weight: 0.15, simulations: 11200, consensusRate: 98.8, stake: "12,500 TAO", status: "active" },
  { id: "Val-0x3C", weight: 0.14, simulations: 10800, consensusRate: 98.5, stake: "11,800 TAO", status: "active" },
  { id: "Val-0x4D", weight: 0.12, simulations: 9600, consensusRate: 97.9, stake: "10,200 TAO", status: "active" },
  { id: "Val-0x5E", weight: 0.11, simulations: 8900, consensusRate: 97.5, stake: "9,500 TAO", status: "active" },
  { id: "Val-0x6F", weight: 0.10, simulations: 8200, consensusRate: 96.8, stake: "8,800 TAO", status: "syncing" },
  { id: "Val-0x7G", weight: 0.10, simulations: 7800, consensusRate: 96.2, stake: "7,200 TAO", status: "active" },
  { id: "Val-0x8H", weight: 0.10, simulations: 7100, consensusRate: 95.8, stake: "6,900 TAO", status: "active" },
];

export const emissionData = [
  { epoch: "E-1", miners: 320, validators: 180, total: 500 },
  { epoch: "E-2", miners: 345, validators: 190, total: 535 },
  { epoch: "E-3", miners: 380, validators: 200, total: 580 },
  { epoch: "E-4", miners: 360, validators: 195, total: 555 },
  { epoch: "E-5", miners: 410, validators: 210, total: 620 },
  { epoch: "E-6", miners: 430, validators: 220, total: 650 },
  { epoch: "E-7", miners: 450, validators: 230, total: 680 },
  { epoch: "E-8", miners: 470, validators: 240, total: 710 },
  { epoch: "E-9", miners: 490, validators: 245, total: 735 },
  { epoch: "E-10", miners: 510, validators: 250, total: 760 },
  { epoch: "E-11", miners: 530, validators: 260, total: 790 },
  { epoch: "E-12", miners: 555, validators: 270, total: 825 },
];

export const vulnerabilityReports = [
  {
    id: "VR-001",
    contract: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",
    protocol: "UniSwap V3 Fork",
    risk: "critical" as const,
    title: "Reentrancy Attack in withdraw() Function",
    description: "The withdraw() function does not follow the checks-effects-interactions pattern, allowing recursive calls that drain the contract balance.",
    line: 142,
    codeSnippet: `function withdraw(uint256 amount) external {\n  require(balances[msg.sender] >= amount);\n  // BUG: State update after external call\n  (bool success, ) = msg.sender.call{value: amount}("");\n  require(success);\n  balances[msg.sender] -= amount; // Should be BEFORE call\n}`,
    estimatedLoss: "$4.2M",
    minerFound: "Miner-0xA3f9",
    validatorConfirmed: 7,
    timestamp: "2024-01-15 14:32:01 UTC",
    status: "confirmed",
  },
  {
    id: "VR-002",
    contract: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
    protocol: "LendFi Protocol",
    risk: "critical" as const,
    title: "Oracle Price Manipulation via Flash Loan",
    description: "Price oracle relies on single-block TWAP, making it vulnerable to flash loan manipulation in the borrow() function.",
    line: 287,
    codeSnippet: `function getPrice() public view returns (uint256) {\n  // BUG: Spot price, not TWAP\n  (uint112 r0, uint112 r1,) = pair.getReserves();\n  return (r1 * 1e18) / r0; // Manipulable!\n}`,
    estimatedLoss: "$12.8M",
    minerFound: "Miner-0x8B2c",
    validatorConfirmed: 6,
    timestamp: "2024-01-15 15:01:44 UTC",
    status: "simulating",
  },
  {
    id: "VR-003",
    contract: "0xdead0000000000000000000000000000000F1a23",
    protocol: "YieldVault DAO",
    risk: "medium" as const,
    title: "Unchecked External Call in stake() Function",
    description: "External call return value is not checked, potentially allowing silent failures that lead to accounting discrepancies.",
    line: 98,
    codeSnippet: `function stake(uint256 amount) external {\n  token.transferFrom(msg.sender, address(this), amount);\n  // BUG: No return value check\n  totalStaked += amount;\n  userStake[msg.sender] += amount;\n}`,
    estimatedLoss: "$890K",
    minerFound: "Miner-0xC7d1",
    validatorConfirmed: 5,
    timestamp: "2024-01-15 15:28:12 UTC",
    status: "confirmed",
  },
  {
    id: "VR-004",
    contract: "0x3333000000000000000000000000000007e1C400",
    protocol: "NFT Marketplace Pro",
    risk: "low" as const,
    title: "Potential Front-Running in bid() Function",
    description: "Bid submissions are visible in mempool before inclusion, allowing MEV bots to front-run legitimate bids.",
    line: 203,
    codeSnippet: `function bid(uint256 tokenId) external payable {\n  require(msg.value > highestBid[tokenId]);\n  // No commit-reveal scheme\n  highestBid[tokenId] = msg.value;\n  highestBidder[tokenId] = msg.sender;\n}`,
    estimatedLoss: "$45K",
    minerFound: "Miner-0xF9a2",
    validatorConfirmed: 4,
    timestamp: "2024-01-15 16:05:33 UTC",
    status: "confirmed",
  },
];

export const networkStats = {
  totalMiners: 1247,
  totalValidators: 64,
  contractsScanned: 89432,
  exploitsFound: 3891,
  totalBountyPaid: "$14.2M",
  avgResponseTime: "1.8s",
  uptime: "99.97%",
  activeAudits: 342,
};
